@base_url = http://127.0.0.1:8000
@admin_token = admin-1
@user_token = user-2

### Search orders
GET {{base_url}}/api/admin/orders
    ?query=
    &status=4
    &user_id=
    &start=2025-06-13
    &end=
    &min=1000000
    &max=5000000
    &page=1&size=10
    &sort=orders_at:desc
Authorization: Bearer {{admin_token}}

### Get order details
GET {{base_url}}/api/admin/orders/1
Authorization: Bearer {{admin_token}}

### Get order status
GET {{base_url}}/api/admin/orders/1/status
Authorization: Bearer {{admin_token}}

### Update order status
PATCH {{base_url}}/api/admin/orders/1/status
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "status": 2
}

### Cancel order (admin)
DELETE {{base_url}}/api/admin/orders/1/cancel
Authorization: Bearer {{admin_token}}
