@base_url = http://127.0.0.1:8000
@admin_token = admin-1
@user_token = user-2

### search products (admin)
GET {{base_url}}/api/admin/products
    ?query=&category=1
    &status=1
    &price_min=0&price_max=100000000
    &page=3&size=15
    &sort=created_at:desc
Accept: application/json
Authorization: Bearer {{admin_token}}

### Create product
POST {{base_url}}/api/admin/products
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "title": "New Product",
  "meta_title": "New Product",
  "slug": "new-product",
  "price": 199.99,
  "sku": "NEWPROUDCT",
  "quantity": 10,
  "status": 1
}

### Get product (admin)
GET {{base_url}}/api/admin/products/1
Authorization: Bearer {{admin_token}}

### Update product
PUT {{base_url}}/api/admin/products/244
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "title": "Updated Product Title"
}

### Delete product
#DELETE {{base_url}}/api/admin/products/1
#Authorization: Bearer {{admin_token}}

### Update categories for product
PUT {{base_url}}/api/admin/products/1/categories
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "category_ids": [1, 2]
}

### Update tags for product
PATCH {{base_url}}/api/admin/products/1/tags
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "tag_ids": [2, 12]
}

### Adjust inventory
PATCH {{base_url}}/api/admin/products/1/inventories
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "amount": 5,
  "operationType": "increase",
  "reason": "stock correction"
}
