@base_url = http://127.0.0.1:8000
@admin_token = admin-1

### search tags
GET {{base_url}}/api/tags
    ?offset=1&limit=20
    &sort=created_at:desc

### search admin tags
GET {{base_url}}/api/admin/tags
    ?offset=1&limit=20
    &sort=created_at:desc
Authorization: Bearer {{admin_token}}

### Create tag
POST {{base_url}}/api/admin/tags
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "title": "New Tag",
  "meta_title": "New Tag",
  "slug": "new-tag",
  "desc": "Description"
}

### Update tag
PUT {{base_url}}/api/admin/tags/1
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "title": "Updated Tag"
}

### Delete tag
#DELETE {{base_url}}/api/admin/tags/1
#Authorization: Bearer {{admin_token}}
