@base_url = http://127.0.0.1:8000
@admin_token = admin-1

### List transactions
GET {{base_url}}/api/admin/transactions
Authorization: Bearer {{admin_token}}

### (Optional) Update transaction status
PATCH {{base_url}}/api/admin/transactions/1/status
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "status": 1
}
