@base_url = http://127.0.0.1:8000
@token = user-20

### List my carts
GET {{base_url}}/api/me/carts
Authorization: Bearer {{token}}

### Add cart item
POST {{base_url}}/api/me/carts/items
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "product_id": 1,
  "quantity": 2
}

### Delete cart item
#DELETE {{base_url}}/api/me/carts/items/1
#Authorization: Bearer {{token}}

### Clear cart
#DELETE {{base_url}}/api/me/carts/clear
#Authorization: Bearer {{token}}

### Checkout
PATCH {{base_url}}/api/me/carts/checkout
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cart_id": 1,
  "promo": null
}
