@base_url = http://127.0.0.1:8000
@token = user-305

### Get my profile
GET {{base_url}}/api/me
Authorization: Bearer {{token}}

### Update profile
PUT {{base_url}}/api/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "first_name": "John",
  "last_name": "Doe",
  "phone": "0123456780"
}

### Update password
PUT {{base_url}}/api/me/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "old_password": "password1234",
  "new_password": "password12345"
}
