@base_url = http://127.0.0.1:8000

### Test VNPay IPN callback (simulated success)
GET {{base_url}}/api/payment/vnpay/ipn
    ?vnp_TxnRef=1
    &vnp_Amount=10000000
    &vnp_ResponseCode=00
    &vnp_TransactionNo=14422574
    &vnp_TransactionStatus=00
    &vnp_TmnCode=I8MHTTPG
    &vnp_SecureHash=test_hash
Accept: application/json

### Test VNPay Return URL (redirect to frontend)
GET {{base_url}}/api/payment/vnpay/return
    ?vnp_TxnRef=1
    &vnp_ResponseCode=00
Accept: application/json

### Test VNPay Return URL (payment failed)
GET {{base_url}}/api/payment/vnpay/return
    ?vnp_TxnRef=1
    &vnp_ResponseCode=24
Accept: application/json
